import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import PromptInput from "@/components/PromptInput";
import ClientProvider from "@/components/ClientProvider";

export const metadata: Metadata = {
	title: "AI Image Generator",
	description: "Generated by the PAPAFAM",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body>
				<ClientProvider>
					<Header />

					<PromptInput />

					{children}
				</ClientProvider>
			</body>
		</html>
	);
}
